### ISSUE TITLE
lesser powerful gpu 

### ISSUE THREAD

**Issue by xprabhudayal** [SakanaAI/AI-Scientist#140]
ive been running this model on a high end instance(h100) for a while & i have some doubts..

1. can we use less powerful gpu to run this ai model? like v100. 
2. is this runnable in COLAB PRO having a100?

**Comment by NathanaelTamirat** [comment]
how long will it take on h100? and have you tried on other cheaper GPUs?
and can this project generate papers beside IT related ?

**Comment by BradKML** [comment]
@xprabhudayal You can ask the agent to do more small scale experiments targeting fine-grained issues (e.g. activation functions, classical ML with HPO, easy NLP optimization) rather than reaching all the way into DL territory. When it comes to idea generation others have said it takes "a few hours" (2-4 hours) for more compute-heavy concepts. https://github.com/SakanaAI/AI-Scientist/issues/145
A small thought would be to create a diverse benchmark covering a wider range of common targets.

@NathanaelTamirat Check is (currently it is made for data-centric experiments not physical research) https://github.com/SakanaAI/AI-Scientist/issues/145#issuecomment-2456269340

**Comment by xprabhudayal** [comment]
I have run this agent on Google Colab for free by using the T4 GPU and during the experiment part it has took me around 2 to 3 hours for `Nano GPT lite`(I had reverse the engineer the Colab and opened up a terminal).
I have generated a paper by using the `Qwen 2.5 72B LLM via API`. 

Like the only part which utilizers the GPU is the experiment agent (when using LLM API) which has been seen in the diagram (in the middle section)

**Comment by BradKML** [comment]
@xprabhudayal so only the GPU is used for both writing code and experimentation? Could you share the setup and the time needed for each process (paper fetching, ideation, code-gen, experiment, drafting, reviewing)?
